# Generated by Django 4.2.16 on 2024-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="Unnamed Product", max_length=100),
            preserve_default=False,
        ),
    ]
